name: rss-to-bsky

on:
  schedule:
    - cron: '* 5-23 * * *'
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry Run without posting'
        required: false
        default: 'true'
      lookBackPeriod:
        description: 'Number of hours to look back'
        required: false
        default: '1'
      currentTime:
        description: 'The current runtime ISO string'
        required: false
        default: ''

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npx tsc

      - name: Run
        env:
          FEED_URLS: ${{ secrets.FEED_URLS }}
          BSKY_USERNAME: ${{ secrets.BSKY_USERNAME }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        run: node dist/app.js --dryRun=${{ inputs.dryRun }} --lookBackPeriod=${{ inputs.lookBackPeriod }} --currentTime=${{ inputs.currentTime }}
