name: rss-to-bsky

on:
  schedule:
    - cron: '5 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npx tsc

      - name: Run
        env:
          FEED_URLS: ${{ secrets.FEED_URLS }}
          BSKY_USERNAME: ${{ secrets.BSKY_USERNAME }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        run: node dist/app.js --dryRun=false --lookBackPeriod=1
